name: ðŸ› Bug Report
description: Create a bug report
title:
labels:
  - 'bug'
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report!
        âš ï¸ If you do not use this template, we will simply close your issue.
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: >
        Please provide a detailed description of the bug.
    validations:
      required: true
  - type: textarea
    id: howtoreproduce
    attributes:
      label: How to Reproduce
      description: >
        Describe steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: >
        Describe what was expected to happen.
    validations:
      required: true
  - type: textarea
    id: results
    attributes:
      label: Actual results
      description: >
        Describe what actually happened.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Minimal code example
      description: >
        If applicable, provide a minimal code example to reproduce the bug.
  - type: textarea
    id: output
    attributes:
      label: Error messages
      description: >
        If applicable, provide any error messages or output related to the bug.
  - type: input
    id: os
    attributes:
      label: Operation System
      description: >
        Specify the operating system you are using.
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      description: >
        Specify the version of Python you are using.
    validations:
      required: true
  - type: input
    id: nextcord
    attributes:
      label: Nextcord version
      description: >
        Specify the version of Nextcord you are using.
    validations:
      required: true