name: ✨ Feature request
description: Create a feature request
labels:
  - 'Feature :sparkles:'
  - 'Needs Investigation :mag:'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        ⚠️ If you do not use this template, we will simply close your issue. ⚠️
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when ...
  - type: textarea
    attributes:
      label: Possible Solution
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional Context
      description: If applicable, add any other context or screenshots about the feature request here.